### ISSUE TITLE
VanillaTD.exe Thread Safety on Multi-core processors

### ISSUE THREAD

**Issue by Gerwin2k** [TheAssemblyArmada/Vanilla-Conquer#381]
Notice the following, at least with Tiberian Dawn. MinGW 8.4.0, Win32, DirectDraw Build. 
Crashes pretty soon after entering a game, within one minute, unless:
1 - Using DDRAW.DLL wrapper developed for the original C&C Gold, with single process affinity enabled. Downside is that this wrapper is rather sluggish when used on older laptops. It decreases the framerate considerably. 
2 - Patching the VanillaTD executable with ImageCFG.exe tool, to set process affinity to core no.1. 
3 - Of course the task manager can also be used to set process affinity, at every run, but it is rather unpractical. 

I also tried building an executable with DirectDrawCreate function modified, to select DirectDraw emulation mode instead. But it does not prevent the crashes, at least not on itself. I do not know whether or not SDL2 builds are immune or affected. 

Method 1 and/or 2 are currently a practical workaround.

**Comment by hifi** [comment]
All work is towards the SDL2 build and some changes may have made the ddraw version more unstable. 

We are deprecating the DirectDraw renderer and it only exists for testing regressions. It will be removed completely later when the SDL2 version has proven to be feature complete and performant enough. It will never be as efficient as the DirectDraw one was without more internal changes but we're trying to get it fast enough so that any reasonable PC can run it. 

Thanks for letting us know.

**Comment by Gerwin2k** [comment]
Thanks for the information. Sounds good. 

Today I made an SDL2 build instead. Version c4dfde4 and also 65cf19a. It seemingly disables DirectSound as well, so use of OpenAL was implied.

The SDL2 build does not have the crashes related to multi-threading, that were described in this ticket.

**Comment by hifi** [comment]
I'm closing this as the DirectDraw build is unsupported. Thanks.
