### ISSUE TITLE
I got to install the C&& GOLD(GDI,NOD) CDs before using this project ? 

### ISSUE THREAD

**Issue by xcom169** [TheAssemblyArmada/Vanilla-Conquer#506]
Hello All!

I got to install the C&& GOLD(GDI,NOD) CDs before using this project ? 
I can compile the executable from this project, but installing this old game is really hard. 
I must emulate a CDROM drive, and also emulate Windows 95. Is there any other way to get the assets and run this modern exe from this project  ?

Thanks!

**Comment by hifi** [comment]
Hi,

Yes, you can extract the data files from the CDs or ISO files if you use the freeware release download.

For C&C it's a bit more tedious than RA as some of the files are inside installer archives rather than directly on the CDs so they need to be extracted separately.

We don't yet have an installer or detailed instructions how to do so manually but [this unofficial guide](https://gist.github.com/abcdefg30/a4fe1110c2727c3960e340ae2ce45bc0) for OpenRA seems to be pretty close to what you'd need to do with Vanilla as well with the exception you don't need to extract the contents of `movies.mix` files but instead put them in `nod` or `gdi` folders. All other mix files should reside next to the Vanilla executable.

To extract from the ISO files you can use 7zip and to extract `INSTALL.Z` you need a tool like @OmniBlade's [isextract](https://github.com/OmniBlade/isextract).

We are going to add a complete automated installer later but first write up a guide but haven't got around to do that yet.

**Comment by xcom169** [comment]
Thank you! I'll try this.

**Comment by xcom169** [comment]
Also scores-covertops.mix has to be put next to the exe file?

**Comment by hifi** [comment]
It would be in `covertops` directory with the rest of covert ops stuff but I'm not exactly sure how well loading them works right now.

**Comment by xcom169** [comment]
so, this is the correct structure? 
./
├── aud.mix
├── cclocal.mix
├── conquer.ini
├── conquer.mix
├── covertops
│   └── scores-covertops.mix
├── deseicnh.mix
├── desert.mix
├── gdi
│   └── movies.mix
├── general.mix
├── hallfame.dat
├── local.mix
├── nod
│   └── movies.mix
├── savegame.000
├── savegame.001
├── scores.mix
├── sounds.mix
├── speech.mix
├── temperat.mix
├── tempicnh.mix
├── transit.mix
├── updatec.mix
├── update.mix
├── vanillatd
├── winter.mix
└── winticnh.mix

3 directories, 25 files

**Comment by hifi** [comment]
Looks about right but the covert ops scores needs to be just "scores.mix" if it works at all.

I'm not too familiar with TD data, unfortunately.
