### ISSUE TITLE
Please make Vanilla-Conquer into a core for use with RetroArch

### ISSUE THREAD

**Issue by Ryan14411** [TheAssemblyArmada/Vanilla-Conquer#638]

**Comment by Ryan14411** [comment]
When you choose to use the libretro API, your program gets turned into a single library file (called a ‘libretro core’). A frontend that supports the libretro API can then load that library file and run the app. The frontend’s responsibility is to provide all the implementation-specific details, such as video/audio/input drivers. The libretro core’s responsibility is solely to provide the main program. You therefore don’t have to worry about writing different video drivers for Direct3D, OpenGL or worrying about catering to all possible input APIs/sound APIs/supporting all known joypads/etc. This is none of your concern at the libretro core implementation level.

**Comment by OmniBlade** [comment]
I'm familiar with libretro and have PR'd some small patches to some of their cores a few years ago. However the current structure of the games is unsuited to being converted into a libretro core due to not having a proper single game loop that can be called on a frame by frame basis. If any libretro devs want to take a crack at it though I'd be happy to work with them to get it suitable for inclusion in our repo.
As it stands this is not going to be worked on by the current contributors though.
