### ISSUE TITLE
[TD] General progress question, and dir structure. 

### ISSUE THREAD

**Issue by xcom169** [TheAssemblyArmada/Vanilla-Conquer#681]
Hello All!

Generally speaking TD is currently okay for normal game-play and completion ? 

What are the required dirs, and files for TD binary to work  ? 
As I understood only C&C Remastered Collection works currently ? 

Thanks,

**Comment by OmniBlade** [comment]
Both games should be playable to completion with perhaps minor bugs here and there. If you have an existing installation of TD from the original distributions you should be able to drop the vanillatd.exe (along with SDL2.dll and OpenAL32.dll if you are on windows) into the directory and it should just work as the original binary did. Some things are subject to change, for example save games may not be compatible between builds as we work to rationalise them and make them more cross platform portable, but hopefully that will be a short lived situation.

**Comment by giulianobelinassi** [comment]
Hi, xcom169.

VanillaTD runs quite stable and I've beaten the GDI Campaign already without any crashes. I've seen some problems with the savegame system, but I don't know how well they are since I fixed several memory issues on it.

Please note that things are subject to change and it is possible that savegames do not work after update because we are constantly changing the datastructures to fix bugs and assert cross-platform compatibility for online games,

You can check the required files here: https://github.com/TheAssemblyArmada/Vanilla-Conquer/wiki/Installing-VanillaTD

If you find bugs while playtesting, please report them so we can fix it.

**Comment by xcom169** [comment]
It should be placed next to the dll ? 
![image](https://user-images.githubusercontent.com/17802090/127907237-6b1243a2-7420-456b-ac8a-955ffbd0ee87.png)

**Comment by hifi** [comment]
That is not going to work, you need the exact files in their specified locations as stated on the wiki page.

Create a new empty directory where you put the vanilla executable and then create the directory structure with the files mentioned. You can pull the mix files from the Remaster within `CNCDATA/TIBERIAN_DAWN` if I recall correctly.

Also for the record GitHub issues are not ideal for user support, we have chat rooms for that visible at the top of the README.
