### ISSUE TITLE
C&C95-style Menus?

### ISSUE THREAD

**Issue by OpenRift412** [TheAssemblyArmada/Vanilla-Conquer#919]
A weird discrepancy I noticed when running VanillaTD with C&C95 (installed from CnC-net) is that the menu buttons are still green like in the DOS version instead of the grey metallic texture like they are in regular C&C95. Is there any plan to fix this?

For comparison, here's the two menus:

C&C95 (had to crop on the bottom since I could only screenshot in windowed mode):
![image](https://user-images.githubusercontent.com/29780788/236699921-776ad3f2-bdac-4ca1-a76f-93ca59895d3a.png)

VanillaTD:
![image](https://user-images.githubusercontent.com/29780788/236699804-27d4f923-cec3-4cf7-bf64-dc70f889de15.png)

**Comment by OmniBlade** [comment]
This is a known issue, the code drop didn't include code for the texture fill function that those buttons use in the original code and no one has been bothered to implement an equivalent for it. Personally I like the DOS style scheme since I played the DOS version first and didn't like the change in the C&C95 port.

However if/when we get around to finishing creating a vanilla sole survivor, that will need the texture function as the load screen palette doesn't support the green buttons (they look like a mucky brown instead), so I'll likely backport it at that point and make it optional in TD.

**Comment by hazelnot** [comment]
Fixed by #986
